spring:
  profiles:
    active: dev
  application:
    name: auth-service
  config:
    import: configserver:${CONFIG_URI:http://localhost:8888}
  cloud:
    config:
      profile: dev
      label: main